"""Migrate factory-assembly footprints into an existing routed PCB.

The placement-only board generated by :mod:`build_pcb` is the source of truth
for footprint identity, value, pad nets and JLC/LCSC metadata.  This helper
keeps the reviewed placement and global copper of the routed input wherever a
smaller package can occupy the same component centre.  Track endpoints that
terminate in an old pad are moved to the corresponding new pad centre.

The three former through-hole IR LEDs and their current-limit resistors are a
deliberate exception: direct assembly requires the new side-view SMD placement.
Their four affected nets are returned to the ratsnest for a reviewed reroute.
The authoritative PCB is never overwritten directly.
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from pathlib import Path

import pcbnew


SWITCH_FOOTPRINTS = frozenset({"SW1", "SW2", "SW3", "SW4", "SW6", "SW7"})
REVIEWED_MOVED_FOOTPRINTS = frozenset(
    {
        "D1",
        "D2",
        "D3",
        "R601",
        "R610",
        "R611",
        "C123",
        "C124",
        # The reviewed placement already moves the larger LF reservoir clear
        # of J3 and keeps that functional block visually compact.
        "C505",
    }
)
LOCAL_REROUTE_FOOTPRINTS = frozenset(
    {
        # Retargeting only one end of the former 0603/0805 escape produces
        # unattractive diagonals and, in these dense locations, can cross a
        # neighbouring route.  Keep the compact part at the reviewed centre
        # and rebuild just its short local escape instead.
        "C302",
        "C510",
        "L6",
        "R113",
        "R120",
        "R513",
        "R736",
    }
)
NO_RETARGET_FOOTPRINTS = (
    REVIEWED_MOVED_FOOTPRINTS | SWITCH_FOOTPRINTS | LOCAL_REROUTE_FOOTPRINTS
)
RETURNED_TO_RATSNEST = frozenset(
    {
        "/IR_LED_A1",
        "/IR_LED_A2",
        "/IR_LED_A3",
        "/IR_LED_K",
        "/ESP_EN",
        "/BOOT_N",
        "/USER_BUTTON_A_N",
        "/USER_BUTTON_SELECT_N",
        "/USER_BUTTON_B_N",
        "/PAIR_N",
        "/BOARD_TEMP_ADC",
        "/SPI_MISO",
    }
)

# These short fanouts/vias occupied copper underneath the larger replacement
# lands.  They are intentionally removed and regenerated after migration.
MIGRATION_COPPER_UUIDS_TO_REMOVE = frozenset(
    {
        # L6 surrounding ground fanout.
        "ed6bca05-0a00-4ae8-89b3-3100c67bc22e",
        "58c555ac-c198-4bdb-ae91-d64638c04d69",
        "7564985b-7121-4d6d-b342-62779ca9fcfe",
        "0d6efb21-4997-4157-a392-745748e60a87",
        # SW2 now uses a much smaller two-land switch; this old +3V3 via sits
        # inside the new ground land.
        "b549c77a-638f-495a-9e73-8b615ba0720e",
    }
)


def item_position_mm(position: pcbnew.VECTOR2I) -> tuple[float, float]:
    return pcbnew.ToMM(position.x), pcbnew.ToMM(position.y)


def distance(left: pcbnew.VECTOR2I, right: pcbnew.VECTOR2I) -> float:
    return math.dist(item_position_mm(left), item_position_mm(right))


def get_or_add_net(board: pcbnew.BOARD, name: str) -> pcbnew.NETINFO_ITEM:
    net = board.FindNet(name)
    if net is not None:
        return net
    net = pcbnew.NETINFO_ITEM(board, name)
    board.Add(net)
    return net


def pad_signature(footprint: pcbnew.FOOTPRINT) -> tuple[tuple[str, str], ...]:
    return tuple(
        sorted((pad.GetNumber(), pad.GetNetname()) for pad in footprint.Pads())
    )


def copy_metadata(target: pcbnew.FOOTPRINT, source: pcbnew.FOOTPRINT) -> None:
    target.SetReference(source.GetReference())
    target.SetValue(source.GetValue())
    target.SetFields(source.GetFieldsText())
    # SetFields creates newly introduced procurement properties with default
    # visibility.  Manufacturing metadata belongs in the file/BOM, not on the
    # physical silkscreen.  Value and all auxiliary properties remain hidden;
    # the reviewed reference style is retained separately.
    for name in target.GetFieldsText():
        if name != "Reference":
            target.GetField(name).SetVisible(False)
    target.SetDNP(source.IsDNP())
    target.SetExcludedFromBOM(source.IsExcludedFromBOM())
    target.SetExcludedFromPosFiles(source.IsExcludedFromPosFiles())
    target.SetDuplicatePadNumbersAreJumpers(
        source.GetDuplicatePadNumbersAreJumpers()
    )


@dataclass
class OldPad:
    number: str
    net_name: str
    position: pcbnew.VECTOR2I
    touches: list[tuple[pcbnew.BOARD_ITEM, str]]


def old_pad_records(
    board: pcbnew.BOARD, footprint: pcbnew.FOOTPRINT
) -> list[OldPad]:
    records: list[OldPad] = []
    tracks = [item for item in board.GetTracks() if not isinstance(item, pcbnew.PCB_VIA)]
    for pad in footprint.Pads():
        touches: list[tuple[pcbnew.BOARD_ITEM, str]] = []
        for item in tracks:
            if item.GetNetname() != pad.GetNetname():
                continue
            if pad.HitTest(item.GetStart()):
                touches.append((item, "start"))
            if pad.HitTest(item.GetEnd()):
                touches.append((item, "end"))
        records.append(
            OldPad(
                number=pad.GetNumber(),
                net_name=pad.GetNetname(),
                position=pad.GetPosition(),
                touches=touches,
            )
        )
    return records


def place_like(
    replacement: pcbnew.FOOTPRINT, target: pcbnew.FOOTPRINT
) -> None:
    if replacement.GetLayer() != target.GetLayer():
        replacement.Flip(replacement.GetPosition(), pcbnew.FLIP_DIRECTION_LEFT_RIGHT)
    replacement.SetPosition(target.GetPosition())
    replacement.SetOrientationDegrees(target.GetOrientationDegrees())


def match_new_pads(
    old_records: list[OldPad], replacement: pcbnew.FOOTPRINT
) -> dict[int, pcbnew.PAD]:
    available: dict[tuple[str, str], list[pcbnew.PAD]] = {}
    for pad in replacement.Pads():
        available.setdefault((pad.GetNumber(), pad.GetNetname()), []).append(pad)

    result: dict[int, pcbnew.PAD] = {}
    for index, record in sorted(
        enumerate(old_records),
        key=lambda entry: (entry[1].number, entry[1].net_name, item_position_mm(entry[1].position)),
    ):
        key = (record.number, record.net_name)
        candidates = available.get(key, [])
        if not candidates:
            # The old KMR2 footprints contain two physical pads for each
            # internally commoned contact, while the smaller factory switch
            # has one land per contact.  Reuse that land for the second old
            # pad so any retained escape converges on the same contact.
            candidates = [
                pad
                for pad in replacement.Pads()
                if pad.GetNumber() == record.number and pad.GetNetname() == record.net_name
            ]
            if not candidates:
                raise RuntimeError(
                    f"No replacement pad for {replacement.GetReference()}.{record.number} "
                    f"on {record.net_name}"
                )
        selected = min(candidates, key=lambda pad: distance(record.position, pad.GetPosition()))
        if selected in available.get(key, []):
            available[key].remove(selected)
        result[index] = selected
    return result


def retarget_track_endpoints(
    old_records: list[OldPad], replacement: pcbnew.FOOTPRINT
) -> int:
    matched = match_new_pads(old_records, replacement)
    # A large old pad can contain more than one old pad centre in unusual
    # duplicate-pad footprints.  Keep only the nearest scheduled move for a
    # given copper endpoint.
    scheduled: dict[tuple[int, str], tuple[float, pcbnew.VECTOR2I]] = {}
    for index, record in enumerate(old_records):
        target = matched[index].GetPosition()
        for item, endpoint in record.touches:
            current = item.GetStart() if endpoint == "start" else item.GetEnd()
            key = (id(item), endpoint)
            candidate = (distance(current, record.position), target)
            if key not in scheduled or candidate[0] < scheduled[key][0]:
                scheduled[key] = candidate

    moved = 0
    item_by_id = {
        id(item): item
        for record in old_records
        for item, _ in record.touches
    }
    for (item_id, endpoint), (_, position) in scheduled.items():
        item = item_by_id[item_id]
        if endpoint == "start":
            if item.GetStart() != position:
                item.SetStart(position)
                moved += 1
        else:
            if item.GetEnd() != position:
                item.SetEnd(position)
                moved += 1
    return moved


def replace_footprint(
    board: pcbnew.BOARD,
    donor: pcbnew.BOARD,
    reference: str,
) -> tuple[int, int]:
    existing = board.FindFootprintByReference(reference)
    source = donor.FindFootprintByReference(reference)
    if existing is None or source is None:
        raise RuntimeError(f"Input/donor footprint mismatch for {reference}")

    records = old_pad_records(board, existing)
    removed_local = 0
    if reference in NO_RETARGET_FOOTPRINTS:
        touching = {
            id(item): item
            for pad in existing.Pads()
            for item in board.GetTracks()
            if item.GetNetname() == pad.GetNetname()
            and (pad.HitTest(item.GetStart()) or pad.HitTest(item.GetEnd()))
        }
        for item in touching.values():
            board.Delete(item)
            removed_local += 1
    replacement = pcbnew.Cast_to_FOOTPRINT(source.Duplicate(False))
    if reference not in REVIEWED_MOVED_FOOTPRINTS:
        place_like(replacement, existing)

    board.Delete(existing)
    board.Add(replacement)
    copy_metadata(replacement, source)
    for pad in replacement.Pads():
        pad.SetNet(get_or_add_net(board, pad.GetNetname()))

    if reference in NO_RETARGET_FOOTPRINTS:
        return 0, removed_local
    return retarget_track_endpoints(records, replacement), removed_local


def migrate(board: pcbnew.BOARD, donor: pcbnew.BOARD) -> tuple[int, int, int]:
    board_refs = {footprint.GetReference() for footprint in board.GetFootprints()}
    donor_refs = {footprint.GetReference() for footprint in donor.GetFootprints()}
    if board_refs != donor_refs:
        raise RuntimeError(
            f"Input/donor references differ: missing={sorted(donor_refs - board_refs)}, "
            f"extra={sorted(board_refs - donor_refs)}"
        )

    cleared = 0
    for item in list(board.GetTracks()):
        if item.m_Uuid.AsString() in MIGRATION_COPPER_UUIDS_TO_REMOVE:
            board.Delete(item)
            cleared += 1
    for item in list(board.GetTracks()):
        if item.GetNetname() in RETURNED_TO_RATSNEST:
            board.Delete(item)
            cleared += 1

    replaced = 0
    moved_endpoints = 0
    for reference in sorted(board_refs):
        existing = board.FindFootprintByReference(reference)
        source = donor.FindFootprintByReference(reference)
        assert existing is not None and source is not None
        if existing.GetFPID().GetUniStringLibId() != source.GetFPID().GetUniStringLibId():
            moved, removed = replace_footprint(board, donor, reference)
            moved_endpoints += moved
            cleared += removed
            replaced += 1
        else:
            copy_metadata(existing, source)
            if pad_signature(existing) != pad_signature(source):
                raise RuntimeError(f"Pad-net mismatch without footprint change: {reference}")

    pcbnew.ZONE_FILLER(board).Fill(board.Zones())
    return replaced, moved_endpoints, cleared


def validate(board: pcbnew.BOARD, donor: pcbnew.BOARD) -> None:
    actual = {footprint.GetReference(): footprint for footprint in board.GetFootprints()}
    expected = {footprint.GetReference(): footprint for footprint in donor.GetFootprints()}
    if actual.keys() != expected.keys() or len(actual) != 267:
        raise RuntimeError("Migrated PCB does not contain the expected 267 unique footprints")

    mismatches: list[str] = []
    for reference in sorted(expected):
        left = actual[reference]
        right = expected[reference]
        checks = (
            left.GetFPID().GetUniStringLibId() == right.GetFPID().GetUniStringLibId(),
            left.GetValue() == right.GetValue(),
            left.IsDNP() == right.IsDNP(),
            left.IsExcludedFromBOM() == right.IsExcludedFromBOM(),
            left.IsExcludedFromPosFiles() == right.IsExcludedFromPosFiles(),
            left.GetFieldsText() == right.GetFieldsText(),
            pad_signature(left) == pad_signature(right),
        )
        if not all(checks):
            mismatches.append(reference)
    if mismatches:
        raise RuntimeError("Migrated footprint metadata mismatch: " + ", ".join(mismatches[:20]))

    for reference in REVIEWED_MOVED_FOOTPRINTS:
        left = actual[reference]
        right = expected[reference]
        if (
            left.GetPosition() != right.GetPosition()
            or left.GetLayer() != right.GetLayer()
            or abs(left.GetOrientationDegrees() - right.GetOrientationDegrees()) > 0.001
        ):
            raise RuntimeError(f"{reference} does not use the reviewed SMD IR placement")

    stale_ir = sorted(
        {item.GetNetname() for item in board.GetTracks() if item.GetNetname() in RETURNED_TO_RATSNEST}
    )
    if stale_ir:
        raise RuntimeError("IR nets retained stale copper: " + ", ".join(stale_ir))


def main() -> int:
    hardware_dir = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--donor", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    input_path = args.input.resolve()
    donor_path = args.donor.resolve()
    output_path = args.output.resolve()
    authoritative = (hardware_dir / "PocketLab-Card.kicad_pcb").resolve()
    if not input_path.is_file() or not donor_path.is_file():
        raise RuntimeError("Input and placement-donor PCBs must exist")
    if output_path == authoritative:
        raise RuntimeError("Refusing to overwrite the authoritative PCB directly")
    if output_path.exists() and not args.force:
        raise RuntimeError(f"Output exists; use --force to replace it: {output_path}")

    board = pcbnew.LoadBoard(str(input_path))
    donor = pcbnew.LoadBoard(str(donor_path))
    replaced, moved_endpoints, cleared = migrate(board, donor)
    validate(board, donor)
    pcbnew.SaveBoard(str(output_path), board)

    reloaded = pcbnew.LoadBoard(str(output_path))
    validate(reloaded, donor)
    print(
        f"Saved factory-footprint migration: {output_path}; replaced={replaced}; "
        f"retargeted_endpoints={moved_endpoints}; cleared_items={cleared}; "
        f"tracks={len(list(reloaded.GetTracks()))}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
