[platformio]
default_envs = pocketlab_card_v1

[env:pocketlab_card_v1]
platform = espressif32
board = esp32-s3-devkitc1-n8r2
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DPOCKETLAB_CARD_HW_REV=1
    -DPOCKETLAB_ALLOW_SUBGHZ_TX=0
    -DPOCKETLAB_ALLOW_IR_TX=1
    -DPOCKETLAB_ALLOW_GPIO_OUTPUT=0
lib_deps =
    links2004/WebSockets@^2.6.1
